version: "3"
services:
  api:
    image: clavico/node_news
    ports:
      - "80:3050"
    links:
      - link-db
  link-db:
      image: mongo
      ports:
        - "27017:27017"
      environment:
        - AUTH=no